### ISSUE TITLE
Rename k8s.io references

### ISSUE THREAD

**Issue by johnsonj** [kubernetes-sigs/addon-operators#28]
per @jwforres [comment](https://github.com/kubernetes-sigs/addon-operators/pull/25#issuecomment-523128543). 

We should replace all references to k8s.io with x-k8s.io to encourage best practices and follow API review guidelines. As we iterate on the individual operators we should look into API review and promotion into k8s.io

/cc @dholbach

**Comment by stealthybox** [comment]
I've moved the `AddonInstallerConfiguration` kind under `addons.config.x-k8s.io` :+1:

**Comment by dholbach** [comment]
This was resolved in 88c0df928cb017462416a127ccaf60f46f4b416c.
