### ISSUE TITLE
Addon operator for core-dns

### ISSUE THREAD

**Issue by dholbach** [kubernetes-sigs/addon-operators#3]
In the first Cluster Addons meeting it was decided to write a addon operator for core-dns. This would be a first concrete step to test the waters, inspire others and get some end-to-end testing mileage out of this.

@justinsb and others (who?) demonstrated interested in this.

**Comment by johnsonj** [comment]
I'm interested in building/helping out with an implementation! (1 of n?)

**Comment by dholbach** [comment]
Thanks @johnsonj - that's great!

**Comment by SataQiu** [comment]
I'm interested in this too.

**Comment by dholbach** [comment]
Nice one @SataQiu!

**Comment by nzoueidi** [comment]
I am interested as well!

**Comment by dholbach** [comment]
We're cancelling the meeting tomorrow (19th April), but maybe let's review some of the code/ideas/approaches in the meeting in two weeks?

**Comment by dholbach** [comment]
Next meeting is tomorrow. Did anyone start work on this and can share some of the code or at least some thoughts?

**Comment by stealthybox** [comment]
See #7 and #8 for kubebuilder and operator-sdk solutions that play with various ideas regarding packaging, reconciliation, interfaces, edge-cases, RBAC, and usability

**Comment by stealthybox** [comment]
Bump -- expect to be resolved by merging #7
