### ISSUE TITLE
Find new meeting time

### ISSUE THREAD

**Issue by dholbach** [kubernetes-sigs/addon-operators#5]
/assign @dholbach

- [x] Review options again (don't clash with other SIG meetings)
- [x] ~~Set up doodle~~
- [x] Ask for objections on mailing list: https://groups.google.com/forum/#!topic/kubernetes-sig-cluster-lifecycle/VXrokx1Kq5U
- [x] Announce change on mailing list and Slack
- [x] Document in [README.md](https://github.com/kubernetes-sigs/addon-operators/blob/master/README.md) and [community repo](https://github.com/kubernetes/community/pull/3506/files): https://github.com/kubernetes-sigs/addon-operators/issues/5#issue-430974609
- [x] Get calendar invite updated

**Comment by dholbach** [comment]
I had a look around and it looks like the 9:00 Pacific Time slot is the sweet spot (17:00 London, 18:00 Berlin).

Consulting the [calendar](https://calendar.google.com/calendar/embed?src=cgnt364vd8s86hr2phapfjc6uk%40group.calendar.google.com&ctz=America/Los_Angeles), it looks like these are our options (to not clash with other meetings of adjacent SIGs):

 - Tuesdays, every 1st/3rd week (alternating with SIG Cluster Lifecycle biweekly), first date would be April 16th.
 - Thursday unfortunately does not work for me at all. It'd be hard for me to manage.
 - Friday would be free too. That'd move us from 10:00 to 9:00. Next date would be April 19th.

8:00 Pacific Time had a lot of free slots, but it's quite early for a quite a few of us, judging by last meeting turnout(?). Not 100% sure.

For reference, [these](https://doodle.com/poll/c8ahkzpsb3vysima) were the results of the last Doodle poll.

@justinsb @errordeveloper Can you comment?

**Comment by errordeveloper** [comment]
> Tuesdays, every 1st/3rd week
👍

**Comment by errordeveloper** [comment]
@dholbach how about another doodle?

**Comment by dholbach** [comment]
Yes. A doodle was my plan. I just wanted to make sure I had your opinion and Justin's before.

**Comment by dholbach** [comment]
This will be too short notice to move the one end of this week (Fri 19th April), so I set up the poll here: https://doodle.com/poll/rpkugi2yg7ntqekf (two options: alternating with SIG Cluster Lifecycle meetings, moving an hour earlier on Fridays).

**Comment by dholbach** [comment]
Looks like Friday 9AM Pacific is kops / sig-aws and so that's the safer bet.

I'll propose this on the SCL mailing list and see if there's objections. Thanks everyone for the feedback so far.

**Comment by dholbach** [comment]
As discussed on the mailing list, we're going with the spot alternating with SIG Cluster Lifecycle meetings.

**Comment by dholbach** [comment]
Done! Next meeting: April 30th, 9:00 PT.
